### ISSUE TITLE
Increase the size of Numbers for Timeouts to match that of Quarter number

### ISSUE THREAD

**Issue by hayrich** [wraus/scoreboardWeb#154]

**Comment by david2202** [comment]
@hayrich Do you mean the size of the numbers or the number of timeouts?

**Comment by nsanders88** [comment]
Hi David,

The size of the numbers (text)please, not the amount of timeouts.

Regards

Nick

Nick Sanders  MAppSc, BAppSc, BTech
Sport Scientist - Performance Analysis Specialist
Victorian Institute of Sport - Australian Paralympic Committee - Shooting Australia

Lakeside Stadium, 33 Aughtie Drive, Albert Park 3206, Victoria, Australia

P: +61 3 9425 0096 M: +61 409 400 280
F: +61 3 9425 0100             E: nick.sanders@vis.org.aumailto:glen.collins@vis.org.au

“SUCCESS IN SPORT AND LIFE”
www.vis.org.auhttp://www.vis.org.au/

On 24 Mar 2016, at 12:47 PM, david2202 <notifications@github.com<mailto:notifications@github.com>> wrote:

@hayrichhttps://github.com/hayrich Do you mean the size of the numbers or the number of timeouts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://github.com/wraus/scoreboardWeb/issues/154#issuecomment-200610110

---

Message protected by MailGuard: e-mail anti-virus, anti-spam and content filtering.
http://www.mailguard.com.au

Report this message as spamhttps://console.mailguard.com.au/ras/1O5Kp6uDCT/3nYGbsOfKAdMT6gizuHkG8/5.644

## 

Message  protected by MailGuard: e-mail anti-virus, anti-spam and content filtering.
http://www.mailguard.com.au

**Comment by david2202** [comment]
Thanks @nsanders88 - I've updated the title to make this clear

**Comment by david2202** [comment]
Fixed in pull request #165
