### ISSUE TITLE
Shot clock and game clock getting out of sync. I have video

### ISSUE THREAD

**Issue by asahani** [wraus/scoreboardWeb#64]

**Comment by david2202** [comment]
I think this is because the shot clock and main clock track independently to an accuracy of a tenth of a second.  If you reset the shot clock to 15 seconds while the game clock is on 50.5 seconds then they will both start counting down from those points when you click start.  This means the display will change half a second out of sync.

Have labelled as wontfix but will leave open today in case anyone else has a different opinion.

@wraus/scoreboard-devs

**Comment by hayrich** [comment]
it is possible for clocks to get out of synch as they are separate clocks, if either scoreboard or scorer tab is inactive clock will stop. 
Clocks are re-synced on every command received from scorer.
